builtin-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin
  artifacts:
    when: always
    paths:
    - build_*/test.log.gz
    - build_*/test_output_np*/*/xunit.xml

builtin-gcc9-optional-libs:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin -f optional-libs
  artifacts:
    paths:
    - build_*/test.log.gz
    - build_*/test_output_np*/*/xunit.xml

epetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k epetra
  artifacts:
    paths:
    - build_*/test.log.gz
    - build_*/test_output_np*/*/xunit.xml


eigen-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k eigen
  artifacts:
    paths:
    - build_*/test.log.gz
    - build_*/test_output_np*/*/xunit.xml

