job-builtin-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin

job-epetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k epetra

job-tpetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k tpetra


job-petsc-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k petsc


job-eigen-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k eigen

