job-builtin-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin
  artifacts:
    paths:
      - build_gcc9-openmpi_*/test.log.gz
      - build_gcc9-openmpi_*/test_output*/*/xunit.xml
    reports:
      junit: xunit.xml

job-epetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k epetra

job-tpetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k tpetra


job-petsc-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k petsc


job-eigen-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k eigen

