.job_template: &phist_artifacts
  artifacts:
    when: always
    paths:
    - build_*/test.log.gz
    - build_*/test_output_np*/*/xunit.xml

                    
builtin-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin
  <<: *phist_artifacts

builtin-gcc9-optional-libs:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k builtin -f optional-libs
  <<: *phist_artifacts

epetra-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k epetra
  <<: *phist_artifacts

eigen-gcc9:
  tags:
    - ESSEX
  script:
    - ./buildScripts/ci-sc-dlr.sh -e gcc9-openmpi -k eigen
  <<: *phist_artifacts
