#include "phist_jadaOp.hpp"
#include "phist_macros.h"
#include "phist_ScalarTraits.hpp"

#include "phist_gen_s.h"
#include "phist_jadaOp_def.hpp"
#include "phist_gen_d.h"
#include "phist_jadaOp_def.hpp"
#include "phist_gen_c.h"
#include "phist_jadaOp_def.hpp"
#include "phist_gen_z.h"
#include "phist_jadaOp_def.hpp"
