#include "phist_jadaOp.h"
#include "phist_macros.h"

#include "phist_gen_s.h"
#include "phist_jadaOp_def.h"
#include "phist_gen_d.h"
#include "phist_jadaOp_def.h"
#include "phist_gen_c.h"
#include "phist_jadaOp_def.h"
#include "phist_gen_z.h"
#include "phist_jadaOp_def.h"
