
-include ${ESSEX_BASE}/make.inc/Makefile.${ESSEX_PLAT}

OBJ=kernels.o
LIBNAME=libessex_kernels_epetra_${ESSEX_PLAT}.a
HEADER_FILES=../kernels.h ../kernels_decl.h ../gen_*.h

include ${ESSEX_BASE}/make.inc/rules
